#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Writes app/src/main/assets/airlines.tsv, the table behind a flight number's row.

    IATA designator <tab> ICAO code <tab> name

One line for every airline that has both codes. A designator is not unique (LH is Lufthansa and
Lufthansa Cargo): the airline with the most routes comes first, and the first one is the one a
typed number is read as. The airlines come from Virtual Radar Server's standing data, the route
counts from adsb.lol's copy of its route table; both are CC0. Run it again to update. `--check`
only checks the file that is there and needs no network.
"""
import argparse
import collections
import csv
import gzip
import io
import pathlib
import re
import sys
import tempfile
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "app/src/main/assets/airlines.tsv"

# A fixed version of the airline list, so that this script writes the same airlines every time. To update:
# change it, run again. The route table has no versions (it is rebuilt every hour); it only decides which
# of several airlines with one designator comes first, so a line may change places from one run to the next.
VRS_COMMIT = "da1b2d1b4f74ee3cbbdfbb27322b433464276311"    # 2 October 2026
AIRLINES = f"https://raw.githubusercontent.com/vradarserver/standing-data/{VRS_COMMIT}/airlines/schema-01/airlines.csv"
ROUTES = "https://vrs-standing-data.adsb.lol/routes.csv.gz"


def fetch(url: str, keep: bool = True) -> bytes:
    """What is at url, kept in the temp folder so that a second run needs no network."""
    cache = pathlib.Path(tempfile.gettempdir()) / "booklight-airlines"
    file = cache / re.sub(r"[^A-Za-z0-9.]+", "-", url.split("://")[1])
    if not (keep and file.exists()):
        cache.mkdir(parents=True, exist_ok=True)
        request = urllib.request.Request(url, headers={"User-Agent": "Booklight"})
        with urllib.request.urlopen(request, timeout=120) as reply:
            data = reply.read()
        part = file.with_name(file.name + ".part")    # a broken download must not pass for the file
        part.write_bytes(data)
        part.replace(file)
    return file.read_bytes()


def clean(text: str) -> str:
    """One line, single spaces: a tab or a line break inside a field would break the table."""
    return " ".join(text.split())


def build() -> str:
    rows = list(csv.DictReader(io.StringIO(fetch(AIRLINES).decode("utf-8-sig"))))
    routes = collections.Counter()
    with gzip.open(io.BytesIO(fetch(ROUTES)), "rt", encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            routes[r["AirlineCode"]] += 1
    both = [r for r in rows if re.fullmatch(r"[A-Z0-9]{2}", r["IATA"]) and re.fullmatch(r"[A-Z]{3}", r["ICAO"]) and clean(r["Name"])]
    # By designator; within one, most routes first, then the name, so that the order is the same on every run.
    both.sort(key=lambda r: (r["IATA"], -routes[r["ICAO"]], clean(r["Name"])))
    lines = [
        "# Airlines for Booklight's flight row. Three columns, separated by tabs: IATA designator, ICAO code, name.",
        "# Where several airlines share a designator, the one with the most routes comes first.",
        f"# From Virtual Radar Server's standing data (github.com/vradarserver/standing-data at {VRS_COMMIT[:10]}), CC0; see NOTICE.",
        "# Generated by tools/airlines.py; do not edit.",
    ]
    return "\n".join(lines + ["\t".join((r["IATA"], r["ICAO"], clean(r["Name"]))) for r in both]) + "\n"


def entries(text: str) -> list[tuple[int, list[str]]]:
    """(line number, columns) of every row that is not a comment."""
    return [(n, line.split("\t")) for n, line in enumerate(text.split("\n"), 1) if line and not line.startswith("#")]


def problems(text: str) -> list[str]:
    """What is wrong with a table, in words; nothing when it is fine."""
    found, seen = [], set()
    if not text.endswith("\n") or "\r" in text:
        found.append("lines must end with a plain line feed, the last one too")
    for n, cols in entries(text):
        if len(cols) != 3:
            found.append(f"line {n}: {len(cols)} columns instead of 3")
            continue
        iata, icao, name = cols
        if not re.fullmatch(r"[A-Z0-9]{2}", iata):
            found.append(f"line {n}: {iata!r} is not a designator")
        if not re.fullmatch(r"[A-Z]{3}", icao):
            found.append(f"line {n}: {icao!r} is not an ICAO code")
        if icao in seen:
            found.append(f"line {n}: {icao} is in the table twice")
        seen.add(icao)
        if not name.strip():
            found.append(f"line {n}: {iata} has no name")
    if not seen:
        found.append("no entries")
    return found


def summary(text: str) -> str:
    rows = [cols for _, cols in entries(text)]
    return (f"{OUT.relative_to(ROOT)}: {len(rows)} airlines, {len({c[0] for c in rows})} designators, "
            f"{len(text.encode('utf-8'))} bytes")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="check the file that is there; write nothing")
    args = parser.parse_args()
    if args.check:
        try:
            text = OUT.read_bytes().decode("utf-8")
        except (OSError, UnicodeDecodeError) as e:
            print(f"{OUT}: {e}", file=sys.stderr)
            return 1
    else:
        text = build()
    wrong = problems(text)
    for line in wrong:
        print(line, file=sys.stderr)
    if wrong:
        return 1    # and a table with problems is not written
    if not args.check:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_bytes(text.encode("utf-8"))
    print(summary(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
